### ISSUE TITLE
Adding Embed as output

### ISSUE THREAD

**Issue by apathy** [sebveigli/coronavirusupdaterbot#1]
Would really appreciate an embed option (extra if I can customize it to my liking). Really like this project so far.

**Comment by sebveigli** [comment]
> Would really appreciate an embed option (extra if I can customize it to my liking). Really like this project so far.

Absolutely can work on this for you, thanks for the suggestion. Any specific way you’d like to be able to customize the embed (other than computing?). 

I’ll update this issue when the changes are pushed.

**Comment by apathy** [comment]
Thanks for the reply and taking your time to implement it. A way to customize the look of the embed would be nice so for example using Flags (just an example, not necessary) instead of text.

**Comment by sebveigli** [comment]
Hey @apathy - FYI, Embed's will be added in this weekend (with a bunch of configuration options alongside it). Unfortunately work has been crazy this past week so haven't had time to work on the bot, but should be all good over the weekend.

**Comment by apathy** [comment]
@sebveigli Thanks a lot, really appreciate all the updates and work towards the bot on your free time. Completely unrelated but it seems like the bot doesn't ping anymore wondering if you have the same issue or if it's fine from your end. Thanks again.

**Comment by sebveigli** [comment]
@apathy just took a look - the source once again changed the way that the represent the data on their side. They concatenated both the China and Rest of World tables into a singular table. I've opened up #4 and working on the fix now, should be pushed in an hour or so.

Embed's coming after that!

**Comment by sebveigli** [comment]
@apathy - Embed option has been added into the bot for output - please take a look and report any bugs/issues or suggestions for improvements. The notification should look something like the following (assuming the country that has been updated has a valid flag link in my mapper).

You can modify some of the attributes of the embed in config/embed.py (i.e. colour, fields).

![Screen Shot 2020-03-07 at 17 56 01](https://user-images.githubusercontent.com/9366479/76147491-ffbd9280-609c-11ea-960a-84ae38684bca.png)

**Comment by apathy** [comment]
@sebveigli Thanks a lot for the updates, was going to comment on the false updates/duplicates but seems like you fixed that already. Will test the embed update now.

**Comment by sebveigli** [comment]
@apathy yeah realized pretty quickly that I was getting duplicates all over the place! Turns out the source link has got some reference tag in it that changes on each refresh, so needed to remove the field but will have it back in eventually. 

I plan to tinker around with the embedding over the next couple of days so let me know your feedback (as well as anything else you’d like in the bot!) :)

**Comment by apathy** [comment]
@sebveigli Really appreciate it, after I saw an embed that I actually like something that looks like this would look nice. Could send you an embed that I made that looks similar to that.

![image](https://user-images.githubusercontent.com/12659760/76153491-d709bd00-60dd-11ea-9dbe-65bee5b17053.png)

**Comment by sebveigli** [comment]
Looks good @apathy ! Going to be doing some pretty big changes code-wise over the next few days, so will definitely look at having that implemented (or at least a way to "design your own" easier)

Planning to:

- Use other (more reliable?) sources
- Have some commands available
- Better structured/maintainable code
- More customisability in terms of how the bot reports
- ... anything that you feel would be worthwhile
