### ISSUE TITLE
Crashing on new update

### ISSUE THREAD

**Issue by apathy** [sebveigli/coronavirusupdaterbot#2]
![image](https://user-images.githubusercontent.com/12659760/75713044-17ca9600-5cda-11ea-98fe-cc57e7aed5e6.png)
Had this issue yesterday as well when running for around an hour.

**Comment by sebveigli** [comment]
Sorry about this @apathy - realised the day before and pushed a fix for this specific change. Also pushed another change today (sometimes the updates were coming in with values like 256*), so now I just replace all non-integer characters from strings and there should be no further issues.

Thanks for raising this.

**Comment by apathy** [comment]
Didn't mean to close this. Any idea why it's still happening?
![image](https://user-images.githubusercontent.com/12659760/75814584-0e593080-5da3-11ea-869b-a86d0003d6c2.png)

**Comment by sebveigli** [comment]
Looks like BNO updated the formatting/DOM of their table which has broken my scraper.. :( I'll take a look at this ASAP and get a fix out - will open up an issue specific for this issue.
