### ISSUE TITLE
Scraper broken due to DOM changes on BNO

### ISSUE THREAD

**Issue by sebveigli** [sebveigli/coronavirusupdaterbot#3]
As reported by @apathy, the scraper can no longer find the table elements on the page due to some changes in the formatting at the source.

The scraper needs to be updated to find these new elements.

**Comment by sebveigli** [comment]
@apathy - I've pushed the changes that should get the bot up & running again. BNO decided to embed an iframe into their page which pulls data stored on Google Docs. I've made the changes necessary to get it up and running, could you please run it and test it and let me know if you run into any further issues (hopefully they won't change the structure again :))

There are some new dependencies, so please remember to pip install -r requirements.txt before next execution.

**Comment by apathy** [comment]
@sebveigli Thanks a lot for the update. Seems to be working perfect for now, will let you know if anything breaks (or not) while I leave it running overnight.

**Comment by apathy** [comment]
@sebveigli For the first 5-10 minutes everything worked, but while leaving it on overnight it randomly broke (this was an issue from the beginning).

![image](https://user-images.githubusercontent.com/12659760/75857532-6c1f6400-5e07-11ea-9d88-7eec2d3c5051.png)

Don't know if its from my part but from testing without changing the text format and leaving it running for a long period of time, it randomly breaks with the same error I posted. Thanks again.

**Comment by sebveigli** [comment]
@apathy yeah that issue is because of your custom formatting - you should remove {notes} from the strings. I removed this because of the new formatting, the new table that BNO provides actually doesn’t store notes in the same way, they just added 3 extra columns in the table for note information. 

I’ll get those added into the updates eventually, just it was super late last night :( Just remove any cases of {notes} in the text update strings and you should be fine - my bot has been up all night working fine 👍🏼

**Comment by apathy** [comment]
Has been working perfectly for the past few hours, thanks a lot.
